### ISSUE TITLE
Output is in ES6 if object spread properties are used

### ISSUE THREAD

**Issue by gera2ld** [rollup/rollup-plugin-typescript#106]
tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs"
  }
}
```

Input:
```ts
const a = {};
const b = { ...a };

export { a, b };
```

Output:
```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

const __assign = Object.assign || function (target) {
    for (var source, i = 1; i < arguments.length; i++) {
        source = arguments[i];
        for (var prop in source) {
            if (Object.prototype.hasOwnProperty.call(source, prop)) {
                target[prop] = source[prop];
            }
        }
    }
    return target;
};

var a = {};
var b = __assign({}, a);

exports.a = a;
exports.b = b;
```

The `const` in output is unexpected.

**Comment by gera2ld** [comment]
Thanks @fightingcat , it works but I don't think it's a good idea to import another library with many helpers just because I am using one of them.
I prefer #99 to be merged.

**Comment by YowaiCoder** [comment]
@gera2ld This is not much an "another library", it's an official typescript helper library, since rollup will eliminate codes you don't use, this is same as the usual way, even better because it's always latest.

**Comment by gera2ld** [comment]
Wow I didn't see it has an entry as ES6. In this case only helpers being used will be imported. It's good to use in this way. Thanks a lot @fightingcat . I think this should be added to the document.

**Comment by owen-m1** [comment]
The solution did not work for me
