### ISSUE TITLE
Looking forward to an index.d.ts

### ISSUE THREAD

**Issue by HadiChen** [rollup/rollup-plugin-typescript#137]
Looking forward to an index.d.ts
![image](https://user-images.githubusercontent.com/11555571/55456547-e1901c80-5619-11e9-8ea9-c96e75f770ed.png)

**Comment by yuchonghua** [comment]
https://github.com/rollup/rollup-plugin-typescript/issues/54

**Comment by shellscape** [comment]
This will be resolved by #138
