### ISSUE TITLE
Typescript errors are not reported to user

### ISSUE THREAD

**Issue by flyingmutant** [rollup/rollup-plugin-typescript#2]
Errors that tsc would show are silently dropped. Spotted in https://github.com/rollup/rollup/issues/280.

**Comment by LabEG** [comment]
- same problem

**Comment by Victorystick** [comment]
This issue stems from not setting the `reportDiagnostics` property of `transpileOptions` to `true`, see https://github.com/Microsoft/TypeScript/issues/5790#issuecomment-159770074. I'll see what I can do.

**Comment by sam-s4s** [comment]
Is there any fix for this?

Currently even fatal compile errors are not being reported for me...
