### ISSUE TITLE
Angular2 app bundling: errors from tippex

### ISSUE THREAD

**Issue by pkozlowski-opensource** [rollup/rollup-plugin-typescript#27]
Today I've manged to go though all the steps of packaging an Angular2 application with Rollup but had to resort to few hacks, one of the problems being https://github.com/Rich-Harris/tippex/issues/1. 

I'm opening the issue here as maybe we can find another solution not involving tippex (or even if it is fixed on the tippex side we still need a test case + version bump).

**Comment by Victorystick** [comment]
@pkozlowski-opensource I tried to bundle Angular2 itself, and hacked around the tippex issue, but soon encountered other, more difficult problems that I've now outlined in #28. I'd really appreciate any input you might have.

Tippex can be completely removed from the plugin once TypeScript handles `ES2015` modules along the `ES5` script target.

**Comment by sonicoder86** [comment]
@Victorystick with Typescript 2.0-dev it is allowed to use ES2015 modules with ES5 target

**Comment by tamascsaba** [comment]
@Victorystick ??

**Comment by PaulBGD** [comment]
Looking into this personally, should have a fix in #91 once I figure it out.
