### ISSUE TITLE
Different behaviour for importing typescript modules to importing js modules

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup-plugin-typescript#3]
I have two comments here. They might both be by design but both confused me.

I am bundle jasmine tests using rollup. Before changing to typescript the following worked very nicely with javascript

``` js
import * as vector_test from "./vector_test";

describe("Level Application; ", function() {

  it("it should have a working test", function() {
    expect(true).toEqual(true);
  });
});
```

However I had to make some unexpected changes to switch to using typescript. There were
1. requiring a file extension. would it be possible/advisable for bundling ts files to look for more ts files by default
2. I actually have to use the import otherwise it is not included. This seams confusing seeing as it is not the case with the js version

``` ts
/// <reference path="./jasmine.d.ts" />
import * as vector_test from "./vector_test.ts"; 
vector_test

describe("Level Application; ", function() {

  it("it should have a working test", function() {
    expect(true).toEqual(true);
  });
});
```

**Comment by flyingmutant** [comment]
> I actually have to use the import otherwise it is not included. This seams confusing seeing as it is not the case with the js version

Isn't this the whole point of rollup — it only includes what you actually use?

**Comment by CrowdHailer** [comment]
Maybe.

In that case it is an error the way rollup without plugin works.

To my mind I have been using import \* as I want everything, and import {A, B, F } to mean leave out functions C,D,E

**Comment by Victorystick** [comment]
@CrowdHailer Do you mean that you _can't_ write `import { A, B, F } from ...`? That it only works with `import * as ...`? That's not intended behaviour.

As to file extensions, it's best practice to include them, and there's currently no option for setting a default file extension.

**Comment by CrowdHailer** [comment]
Ok so I don't mind including file extensions that's not a problem.

In my example the vector_test file doesn't have any exports. What I want to do is include it so the code in it is run.
That code is tests so I don't need a handle to them. I just need them included in the bundle so that when I run the bundle all the tests are run

**Comment by Victorystick** [comment]
Try importing the tests for their side-effects: `import './vector_test.ts';`

**Comment by CrowdHailer** [comment]
That was exactly what I needed thank you

**Comment by Victorystick** [comment]
Glad to hear it!
