### ISSUE TITLE
tsconfig support

### ISSUE THREAD

**Issue by RReverser** [rollup/rollup-plugin-typescript#35]
I'm wondering if it would be possible to make this plugin support [`tsconfig.json`](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) so that it would be possible to use it in configuration-less fashion just like [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel) can be used with `.babelrc`.

**Comment by Victorystick** [comment]
@RReverser I haven't investigated that option, but I'm sure it's possible. I'll look into it.

**Comment by RReverser** [comment]
So far I just tried to use `project: '.'` (as I would with normal TS API), but it didn't work - I suspect due to conflict when merging options in the plugin or maybe some other reason. Thanks!

**Comment by kalahari** [comment]
I think your best option may be a variation on:
`const compilerOptions = require('./tsconfig.json').compilerOptions;`
that is extended with any rollup specific options.

**Comment by RReverser** [comment]
@kalahari Except that JSON has options in serialized form, whilst `rollup-plugin-typescript` talks directly to TS API and thus needs to use actual enum values: https://github.com/rollup/rollup-plugin-typescript/blob/master/src/index.ts#L58-L61

Moreover - those values override options that you pass, so that won't work either.

And native support would be much better anyway.

**Comment by giladgray** [comment]
+1. I can't realistically use this plugin until it has `tsconfig.json` support.

**Comment by Victorystick** [comment]
This has been released as `0.7.0`.
