### ISSUE TITLE
Phantom Error when trying to compile with target ES6

### ISSUE THREAD

**Issue by alexandertrefz** [rollup/rollup-plugin-typescript#37]
I have a small project that i am compiling with rollup in multiple ways - basically I compile an output file for every possible target. They all compile and work just fine, except when I use ES6 as a target, in which case it tells me that it finds an `Unexpected token (7:50)` in a file, but line 7 doesnt even have 50 columns in that file. Tinkering with the any of the files of that project does not change the reported location of the error. All other targets work, using `tsc` directly works without error as well. I also have used the same rollup config on another project where all the compiles work just fine.

Can you hint me towards debugging this maybe? Is there any kind of verbose mode for rollup so that i can get more context for the error it finds?

**Comment by Victorystick** [comment]
I'm sorry, I've no idea why it doesn't work. It doesn't seem related to the known issues (#28), although you could investigate that.

Unfortunately, Rollup doesn't display the code at the location of errors. There is a [tracking bug](https://github.com/rollup/rollup/issues/296) for this feature.

**Comment by alexandertrefz** [comment]
Looking at #28 I don't think my issue is related to it, I am not using any of the features mentioned in that issue.

Just for tracking and understanding this better in the future I will just mention again that this `only happens when compiling to the ES6 module format`, not for any of the other formats. So I will venture the guess that it is closely related to a code path dealing with that.

**Comment by PaulBGD** [comment]
I'm going to close this as it's rather old, but if you have code that can trigger this error please add a comment and I'll reopen the issue.
