### ISSUE TITLE
Overriding TypeScript version

### ISSUE THREAD

**Issue by pkozlowski-opensource** [rollup/rollup-plugin-typescript#4]
[Docs](https://github.com/rollup/rollup-plugin-typescript/blob/master/README.md#issues) are stating that TS version used by this plugin can be easily overridden giving this code snippet as an example:

```
import typescript from 'rollup-plugin-typescript';
import * as ts from 'typescript';

export default {
  entry: 'main.ts',

  plugins: [
    typescript({
      target: ts.ScriptTarget.ES6
      sourceMap: true
    })
  ]
}
```

Is importing `import * as ts from 'typescript';` enough to override tsc version? If so, what kind of node black magic would be involved here? I've played with this locally and couldn't override TS version.

Is there are clever trick at play here or is the override option missing from the impl?

**Comment by Victorystick** [comment]
Only the target ECMAScript version can be overridden. The `tsc` version is currently an 1.7.0 beta I got from npm. Do you want to use a later version?

**Comment by pkozlowski-opensource** [comment]
> The tsc version is currently an 1.7.0 beta I got from npm. Do you want to use a later version?

Yes. I'm hitting some TS bugs with the tsc version bundled with rollup-plugin-typescript and would like to be able to switch between / use a particular TS version. Something along the lines of what is possible with the `gulp-typescript` plugin: https://github.com/ivogabe/gulp-typescript#typescript-version

I can send a PR of this makes sense

**Comment by Victorystick** [comment]
Oh, I see. Yes, that's probably a good idea. A PR would be lovely. :smile:
