### ISSUE TITLE
fixExportClass.ts no longer works.

### ISSUE THREAD

**Issue by texastoland** [rollup/rollup-plugin-typescript#44]
Using `typescript@next` I get the following:

``` ts
export class A{}           // A = A;
class A{};export {A}       // ;\nexport {A};
export default class A{}   // exports["default"] = A;
class A{};export default A // export default A;
```

**Comment by Victorystick** [comment]
@AppShipIt Can you elaborate on the problem? I can't really tell what input code resulted in what output.

Also, I believe `export A` is invalid syntax; did you mean `export { A }`?

**Comment by texastoland** [comment]
> did you mean `export { A }`?

Corrected thanks!

> what input code resulted in what output.

From a shell session with a recent drop of TS 1.9:

``` shell
$ ./node_modules/typescript/bin/tsc --version
Version 1.9.0-dev.20160428-1.0

$ INPUT='export class A{}'

$ node -e "
> const ts=require('typescript');
> console.log(ts.transpileModule('$INPUT',{
> compilerOptions:{module:ts.ModuleKind.ES2015}
> }).outputText)"
var A = (function () {
    function A() {
    }
    return A;
}());
A = A;

$ INPUT='class A{};export {A}'

$ node -e "const ts=require('typescript');console.log(ts.transpileModule('$INPUT',{compilerOptions:{module:ts.ModuleKind.ES2015}}).outputText)"
var A = (function () {
    function A() {
    }
    return A;
}());
;
export { A };
```

Repeating each variation from the description should yield my commented text as the last line.

> Can you elaborate on the problem?

Looking again (with more rest) your regex will just skip `export [default] <name>` versions. But I wanted to share it may begin failing on `export [default] class <name>`.

**Comment by Victorystick** [comment]
Have you tried overriding the TypeScript version used by the plugin to test this? I think the plugin should be handling this.

``` js
typescriptPlugin({
  typescript: require('typescript')
})
```

**Comment by texastoland** [comment]
Oh I see what you're doing my bad!
