### ISSUE TITLE
Doesn't work with "strictNullChecks"

### ISSUE THREAD

**Issue by ghost** [rollup/rollup-plugin-typescript#46]
Hey.

**TypeScript version**: `1.9.0-dev.20160613-1.0`.

If I set strictNullChecks in the `tsconfig.json` to a boolean value, and not using any configuration in the plugin - `typeScript({})` - it throws this:  `Unknown compiler option strictNullChecks`.

If I add some configuration to this, and set target to es5 and module to es6 plus set declaration to false within the plugin itself, and set it to use the TC 2 dev. Everything works.

The performance seems to getting worse also comparing to native TSC when you set the TS inline as an plugin option. 4 - 5 ms vs 2 - 3 ms native. 

For me it seems that this plugin doesn't work with latest TS 2.0 Pre version? And I think this is the source for the issue? https://github.com/rollup/rollup-plugin-typescript/blob/master/package.json#L34

This plugin also uses itself as a dev dependency with a much older version of the plugin, and older version of Rollup.

**Comment by ghost** [comment]
Any solution on this issues?

**Comment by Victorystick** [comment]
Just published version 0.7.6. Let me know if you run into any other issues.
