### ISSUE TITLE
Typescript forgotten helper __assign

### ISSUE THREAD

**Issue by MartynasZilinskas** [rollup/rollup-plugin-typescript#49]
After "bundling" code `__assign` typescript-helper is missing.
![image](https://cloud.githubusercontent.com/assets/562658/16876663/716804c4-4aad-11e6-9b40-4de67e4511a1.png)

**Comment by Victorystick** [comment]
The TypeScript `__assign` helper still wasn't around when we started bundling the helpers. Fortunately, it appears that Microsoft have created [tslib](https://github.com/Microsoft/tslib) which contains the [complete set of ES6 helpers](https://github.com/Microsoft/tslib/blob/master/tslib.es6.js) that will be maintained by the TypeScript devs. We should definitely prefer that over our local copy.

**Comment by Victorystick** [comment]
Hmm... Sadly, they've decided against including the `__extends` helper in the ES6 version of `tslib`. What a shame. They likely assume that `tslib.es6.js` will only be used in environments with native `class` support; which excludes us.

I guess we'll just add the `__assign` helper ourselves for now.

**Comment by Victorystick** [comment]
@MartynasZilinskas Are you using a nightly build? Object spread doesn't seem to be due until the next TypeScript release.

**Comment by MartynasZilinskas** [comment]
Hey @Victorystick. Thanks for your fast response. I am currently using 1.8.10 version.

**Comment by Victorystick** [comment]
Released as `0.7.7`!
