### ISSUE TITLE
Usage examples in the readme

### ISSUE THREAD

**Issue by CrowdHailer** [rollup/rollup-plugin-typescript#5]
This might be a silly question.

I can't get the usage examples to work as show on this repo's README.

The problem I get is `SyntaxError: Unexpected token import`

When I rewrite the example to use the commonjs module format It all works properly. The version of node I am running is v5.1.0

I assume that my version of node does not yet support es6 module syntax. But I have updated it to the latest. I have tried running the example using the `--harmony_modules`, which also does not work.

Should the examples work with default node?
Or are the code examples actually in typescript and you are running them via tsc?
Or is there an es6 compile step necessary to run the example code?

**Comment by Victorystick** [comment]
The examples are `rollup.config.js` files that get processed by Rollup before execution. Try them out using `rollup -c`!

**Comment by Victorystick** [comment]
This was clarified in #6
