### ISSUE TITLE
Remove Typescript from dependencies

### ISSUE THREAD

**Issue by cebor** [rollup/rollup-plugin-typescript#50]
Is it possible to remove Typescript from dependencies, so it's not bound to a specific version, and it's possible to use Typescript 2.0.0.

**Comment by amcdnl** [comment]
Agreed, and probably update to TS 2.0

**Comment by cebor** [comment]
Think removing is the better way, so you can decide which version of typescript you want to use.

Or maybe move it to devDeps so the tests will still work.

**Comment by cebor** [comment]
PR: #55

**Comment by emilekberg** [comment]
it is still possible to use typescript 2.0, install it as through npm and do as the readme says.

```
npm install typescript@beta
- then - 
return rollup({
        entry: './src/core.ts',
        plugins: [
            typescript({
                typescript: require('typescript')
            })
        ]
});
```

**Comment by TrySound** [comment]
This "feature" will require user to think more then user should. It's your choice if you want to use different version. One more dependency won't break your life. Upgrade will be someday.

**Comment by alex-kinokon** [comment]
Can we have TypeScript 2.0 now?

**Comment by tabanliviu** [comment]
#81 shows a systematic problem with custom typescript libraries because helpers are hardcoded in the plugin source

**Comment by PaulBGD** [comment]
I'm going to close this as a no, however in the future for another major version I'll consider this. I think it's definitely helpful for a baseline TypeScript version to be installed for the user, however offering the ability to use whatever version you want is something that I support as well.
