### ISSUE TITLE
Tests failed with Rollup 0.34.1

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [rollup/rollup-plugin-typescript#52]
**rollup-plugin-typescript** tests failed with newest rollup version.

``` json
"devDependencies": {
    "mocha": "^2.3.3",
    "rollup": "^0.34.1",
    "rollup-plugin-typescript": "^0.7.6"
  }
```

Npm log:

`````` cmd
$ npm install

> rollup-plugin-typescript@0.7.6 prepublish D:\test\rollup-plugin-typescript
> npm run test


> rollup-plugin-typescript@0.7.6 pretest D:\test\rollup-plugin-typescript
> npm run build


> rollup-plugin-typescript@0.7.6 prebuild D:\test\rollup-plugin-typescript
> rm -rf dist/*


> rollup-plugin-typescript@0.7.6 build D:\test\rollup-plugin-typescript
> npm run build:cjs && npm run build:es6


> rollup-plugin-typescript@0.7.6 build:cjs D:\test\rollup-plugin-typescript
> rollup -c -f cjs -o dist/rollup-plugin-typescript.cjs.js

Treating 'path' as external dependency
Could not resolve ./string from D:\test\rollup-plugin-typescript\src\index.ts
Error: Could not resolve ./string from D:\test\rollup-plugin-typescript\src\index.ts
    at D:\test\rollup-plugin-typescript\node_modules\rollup\src\Bundle.js:244:41
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki```
``````

**Comment by GiedriusGrabauskas** [comment]
In newest [rollup 0.34.1](https://github.com/rollup/rollup) version import doesn't work without files extensions (`.ts`, `.tsx`).

**Comment by Victorystick** [comment]
@GiedriusGrabauskas I have not been able to reproduce that particular error. Regardless, I'll update the plugin to build with a more recent version of Rollup shortly.

**Comment by ghost** [comment]
@Victorystick If you upgrade the NPM packages for this plugin, and try to use latest Rollup you will reproduce the issue. You are still using Rollup 25.x https://github.com/rollup/rollup-plugin-typescript/blob/master/package.json#L38

**Comment by GiedriusGrabauskas** [comment]
Yes, you have to manually upgrade version in `package.json` file.

**Comment by Victorystick** [comment]
@Kflash @GiedriusGrabauskas I did, but still wasn't able to reproduce the issue. I'll take another look this evening.

**Comment by GiedriusGrabauskas** [comment]
Clone my repository: [GiedriusGrabauskas/rollup-plugin-typescript](https://github.com/GiedriusGrabauskas/rollup-plugin-typescript)

And run: `npm install -f`

Using:
- **NodeJS v6.3.0**
- **npm 3.10.5**

**Comment by DovydasNavickas** [comment]
:+1:

**Comment by ghost** [comment]
@GiedriusGrabauskas Look at this issue: https://github.com/rollup/rollup/issues/795 Is this what cause the issue for you? See latest post.

@Victorystick If this is the case, you can't reproduce it if you are using an Mac, but after rolling back the changes locale I didn't have this issue anymore.

**Comment by Victorystick** [comment]
@Kflash Hmm... So you're saying it could be a Windows specific issue with Rollup?

**Comment by DovydasNavickas** [comment]
Well, I and @GiedriusGrabauskas got this on Windows. If @Kflash also had this on Windows, this might just be the case.
I can check on MacOS if needed, but if you @Victorystick tried to reproduce this on MacOS and could not get it to fail, it just raises the chances.

**Comment by ghost** [comment]
@Victorystick You can't reproduce it, and I don't get the issues mentioned here on Mac. But I get them on Windows.  After I rolled back a change done in the Rollup core locale, it worked for me. 
https://github.com/rollup/rollup/issues/795

**Comment by ghost** [comment]
@DovydasNavickas @Victorystick  Rollup 0.33.1 introduced a change that caused this. Rollup v. 0.32.4 and older should work without issues. At least it does that for me. 
However. Rollup v. 0.33.0 also cause issues on one of my Windows computer running latest windows 10, but not on my other computer with older Windows 10.

Hard to tell what's causing this when I look at the changelog. https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0330

But I had an issue generating sourcemap on Windows yesterday too, and one of the commit mention sourcemap. But I doubt this is what causing it.

My time is up now, and no more time to investigate.

**Comment by Victorystick** [comment]
@Kflash I cannot reproduce it on Ubuntu. I'm closing this as it appears to be a Rollup issue.

**Comment by ghost** [comment]
@Victorystick Regarding @TrySound this has to be a bug with this repo. See this issue ticket: https://github.com/rollup/rollup/issues/795

So if the bug isn't in this repo or in Rollup, and @GiedriusGrabauskas @DovydasNavickas  and others also experience this bug with latest Rollup version... ,  I don't know.

**Comment by GiedriusGrabauskas** [comment]
I created pull request https://github.com/rollup/rollup-plugin-typescript/pull/59
