### ISSUE TITLE
typescript-helpers.js shouldn't be included in sourcemap

### ISSUE THREAD

**Issue by ronzeidman** [rollup/rollup-plugin-typescript#61]
This is part of the sourcemap when I use rollup:
`"sources":["../node_modules/rollup-plugin-typescript/src/typescript-helpers.js","..`
since the rollup-plugin-typescript is a devDependency it won't be included when someone imports my library.
This causes issues with bundling sites that uses my library
Example:
https://github.com/ronzeidman/ng2-ui-auth/blob/master/dist/ng2-ui-auth.js.map

**Comment by maxdavidson** [comment]
This was an issue with rollup-plugin-babel that was resolved by adding functionality to rollup for ignoring a file from the sourcemap. See https://github.com/rollup/rollup-plugin-babel/issues/64.

**Comment by TrySound** [comment]
@maxdavidson Thanks. Do you want to create PR with fix and test case?

**Comment by maxdavidson** [comment]
@TrySound Sure, I'll see what I come up with
