### ISSUE TITLE
How to handle *.d.ts

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup-plugin-typescript#62]
Should we strip import with them or handle somehow?
`allowJs` doesn't work with node_modules, which does not let to use typescript as transpiler for angular2 dependencies.
Maybe better to lay on `rollup-plugin-node-resolve` with some cases?

**Comment by StevenDoesStuffs** [comment]
Any updates?

**Comment by thgreasi** [comment]
Any updates?

**Comment by blackcater** [comment]
Any updates?

**Comment by drozdzynski** [comment]
Any updates?

**Comment by nickserv** [comment]
Duplicate of #54
