### ISSUE TITLE
How to generate *.d.ts also?

### ISSUE THREAD

**Issue by kyasbal** [rollup/rollup-plugin-typescript#63]
I specified "declaration" flag true in my tsconfig.json.
But, any *d.ts files would not be generated. 
I guess there is some cases want to generate *.d.ts files before bundling also when we use rollup to bundle them.

**Comment by venil7** [comment]
Any updates on this issue?

**Comment by PaulBGD** [comment]
Merging this into #62 as a general declarations issue.

**Comment by yanhaijing** [comment]
same question, Any updates?
