### ISSUE TITLE
Specify tsconfig.json file

### ISSUE THREAD

**Issue by sam-s4s** [rollup/rollup-plugin-typescript#66]
It doesn't appear that there is any way to specify a custom tsconfig.json path/name.

For example, my project has 2, and the one I want to point this plugin at is called "tsconfig_jit.json".

Would be clean and super handy :)

**Comment by notoriousb1t** [comment]
I put in a pull request for this in PR #71

**Comment by PaulBGD** [comment]
Closing issues that I've integrated into #91, will be merged into master soon.
