### ISSUE TITLE
moment conflict

### ISSUE THREAD

**Issue by tamascsaba** [rollup/rollup-plugin-typescript#68]
When I use moment with rollup-plugin-typescript, throw an error:

``` typescript
import * as moment from "moment";
moment();
```

```
bundle dev started ...
Error: Cannot call a namespace ('moment')
```

I finded a workaround, but is is not compatible with my editor, underline with red line
https://forum.ionicframework.com/t/error-from-rollup-when-importing-moment-js-with-rc0/64902

```
import  moment from "moment";
```

![moment](https://cloud.githubusercontent.com/assets/3479963/19300160/1076fd22-9059-11e6-9b2f-047372191aa8.png)

`Module moment has no default export.`

**Comment by ghetolay** [comment]
My current workaround is using a custom replace plugin like so : 

``` js
plugins: [
  {
    name: 'replace moment imports',
    transform: code =>
      ({
        code: code.replace(/import\s*\*\s*as\s*moment/g, 'import moment'),
        map: { mappings: '' }
      })
  },
  typescript()
]
```

**Comment by aluanhaddad** [comment]
@tamascsaba That is because the namespace import form, `import * as namespace` does not import the call signatures of the target. 
If the following works at runtime, but gives you language service errors, such as in an IDE,

``` ts
import  moment from "moment";
```

Then add `"allowSyntheticDefaultImports": true` to your `tsconfig.json` `"compilerOptions"`

**Comment by tamascsaba** [comment]
thx @aluanhaddad && @ghetolay  :)

**Comment by MarkPerryBV** [comment]
@ghetolay 's rollup plugin worked for me to resolve the issues I was getting.

**Comment by Mariusz-v7** [comment]
@aluanhaddad 

`import  moment from "moment";`

solves the issue but it breaks SystemJS which results in the following message: 

> moment_1.default is not a function

Do you know how to configure SystemJS to work with this kind of import?

**Comment by aluanhaddad** [comment]
Yes but which reversion of SystemJS are you running? it should be working by default  no pun intended. Mapping `module.exports` onto `exports.default` is the standard SystemJS behavior aligning with the ES Module spec and the Node.js plans for adopting a subset of it. I'm curious what your workflow is using SystemJS with rollup-plugin-typescript. 
```js
SystemJS.config({
  packages: {
    "npm:moment": {
      format: "cjs"
    }
   }
  } 
});
```

**Comment by vZanchiV** [comment]
@aluanhaddad 

thx for your solution. now i don't have Error: Cannot call a namespace ('moment').

But i have this error : **Module '"C:/SIte/**i/node_modules/moment/moment"' has no default export.**

i use angular cli. and this error appear when i want build whith npm run packagr :(

you have a idea why i have thos error ?

**Comment by aluanhaddad** [comment]
For those interested, TypeScript now provides the `default` synthesis, similar to Babel, not just the interop awareness that is enabled by `--allowSyntheticDefaultImports`, but the generation of interop code for legacy module formats.

It is behind a new flag `--esModuleInterop` and is available in `typescript@next`.

**Comment by Yogu** [comment]
> That is because the namespace import form, import * as namespace does not import the call signatures of the target.

Why is [this workaround](https://github.com/rollup/rollup/issues/670#issuecomment-355945073) working, then? Seems like a bug in rollup. TypeScript [allows to merge function declarations with namespaces](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-namespaces-with-classes-functions-and-enums), and webpack/ts-node don't have a problem with this. I don't like enabling `--allowSyntheticDefaultImports` just to be able to use these modules with rollup.

**Comment by zanona** [comment]
It feels like having to change the codebase which would then break validation in order to accommodate post-processing is a bit of a let-down. Perhaps this can be reconsidered and @ghetolay's workaround could perhaps be added as part of this plugin? -If that's possible at all
As of now, I believe that's the only solution that looks clean enough and doesn't interfere with the development process to something other than what you would expect when compiling typescript.
