### ISSUE TITLE
Typescript module import is broken since Rollup 0.34.0

### ISSUE THREAD

**Issue by dmitrijs** [rollup/rollup-plugin-typescript#69]
Since version 0.34.0, rollup requires file extensions when importing modules.

However, ".ts" extension should not be used when importing typescript modules, for example:
`import { AppModule } from './app.module';`
see https://www.typescriptlang.org/docs/handbook/modules.html

So now rollup cannot compile the project:

```
D:\Project>rollup -c
Treating '@angular/platform-browser-dynamic' as external dependency
Could not resolve './app.module' from D:\Project\resources\assets\app\main.ts
Error: Could not resolve './app.module' from D:\Project\resources\assets\app\main.ts
    at c:\Programs\nodejs\global_packages\node_modules\rollup\src\Bundle.js:319:41
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

**Comment by plmrry** [comment]
I'm having the same issue – however, is this possibly an issue with `rollup-plugin-node-resolve`? 

https://github.com/rollup/rollup-plugin-node-resolve

**Comment by plmrry** [comment]
I believe this is related to `rollup-plugin-node-resolve`. Are you using it?

My error seems to be coming from [here](https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L67)

Although yours might not...

**Comment by plmrry** [comment]
I think I found a solution: 

Include `.ts` in the `extensions` array of `nodeResolve`.

For example:

``` typescript
var cache;

export default {
  entry: 'src/ic.ts',
  dest: 'bundle.js',
  format: 'iife',
  moduleName: 'foo',
  plugins: [
      nodeResolve({
        jsnext: true,
        extensions: [ '.ts', '.js', '.json' ]
      }),
      typescript({
        typescript: require("typescript")
      }),
      commonjs(),
      json()
  ],
  cache: cache
}
```

However, I'm still interested to know if you're using `rollup-plugin-node-resolve` or not

**Comment by cbruun** [comment]
I am using the node-resolve and typescript plugins and I got the same error as @dmitrijs. The fix from @plmrry works.

**Comment by dmitrijs** [comment]
Also, the order of plugins seems to be important.
I'm get this error if typescript(...) goes after nodeResolve(...) in `plugins` options:

```
Could not resolve 'typescript-helpers' from D:\Project\resources\assets\app\list\Editor.ts
Error: Could not resolve 'typescript-helpers' from D:\Project\resources\assets\app\list\Editor.ts
    at Error (native)
    at D:\Project\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
```

Rollup runs fine if typescript() goes before nodeResolve().

Thanks for help, with proper nodeResolve configuration and some tricks module import works fine, so issue can be closed.
