### ISSUE TITLE
Recurring problem with imports

### ISSUE THREAD

**Issue by TimMensch** [rollup/rollup-plugin-typescript#76]
This problem lies at the intersection between this plugin and rollup-plugin-commonjs, I believe, but it's a serious problem and doesn't happen without TypeScript, so I'm filing it here.

If you use TypeScript and you import a package that's expecting to be used as a function (like socket.io-client or marked), you need to import it like this:

```
import * as marked from "marked";
import * as io from "socket.io-client";
```

...but when imported that way, Rollup will consider `marked` and `io` to be namespaces, and you can't call the function that they represent.

If you try:

```
import marked from "marked";
import io from "socket.io-client";
```

or

```
import { marked } from "marked";
import { io } from "socket.io-client";
```

TypeScript will throw an error based on the standard way that TypeScript definition files are written for both of these packages. The latter probably wouldn't work anyway, since both are exported as the default export.

I get that Rollup is trying to be "correct" in an ES6 import way, but we need Rollup to Just Work here and *not* care that, even though we're using the first import syntax, the item we're importing is actually a raw JavaScript object that can be called as a function, if necessary. 

Currently there's no way that I've found to make these imports work correctly without hacking the type files and sometimes the original package code directly. If there's a way to override Rollup and tell it to just give me the entire exported object without wrapping it in a frozen object, I haven't found it.

So for completeness: If I have a project that is using rollup-plugin-typescript AND rollup-plugin-commonjs AND rollup-plugin-node-resolve, and I want to import a package like "marked" (`npm install marked @types/marked`), there's no current way to do this, because the normal way to use marked is:

```
let marked = require("marked");
let result = marked("some markdown here");
```

And, as far as I can tell, there's no way to get that equivalent functionality in a way that *both* TypeScript and Rollup will work with.

**Comment by eventualbuddha** [comment]
I'm surprised TypeScript allows this. ES module using a namespace import creates a binding which is, by definition, not a function.

**Comment by aluanhaddad** [comment]
```ts
import marked from "marked";
```
If the above behaves correctly at runtime, i.e. marked is not `undefined`, then another transpiler or additional runtime infrastructure, such as Rollup or SystemJS is mapping `module.exports` to `exports.default`. TypeScript _does_ understand this behavior and has a flag specifically designed to model it.

Specify `"allowSyntheticDefaultImports": true` in the `"compilerOptions"` property of your **tsconfig.json**. 

This informs TypeScript that this translation will be performed and thus no errors will be raised and the types will be correct for code such as the following.

**a.ts**
```ts
export = function () { return 1; };
```
**b.ts**
```ts
import a from './a';
a();
```

**Comment by TimMensch** [comment]
@aluanhaddad I didn't understand the implications of your comment at first, and was going to complain about it not working...but then I understood what you were saying, and _yes_, it does work when I do that.

SO just to rephrase for posterity:

If you want to be able to use `import a from 'someModule'`, and you get the TypeScript error `Module '"someModule"' has no default export.`, then you can fix that by enabling `"allowSyntheticDefaultImports": true` in tsconfig.json.

Thanks! Closing the issue now. 😀

**Comment by RikkiGibson** [comment]
This helped me. Might be worth documenting as it strikes me as a common use case.
