### ISSUE TITLE
Incremental compilation and rewriting plugin

### ISSUE THREAD

**Issue by Avol-V** [rollup/rollup-plugin-typescript#79]
This plugin seems useless in current state — it much better to build TypeScript separately and use Rollup only for bundle JS files.

But it hard because there is no oficial option to use Rollup with Gulp, where we can use https://github.com/ivogabe/gulp-typescript — it is a good implementation of plugin for build TypeScript.

We need a full support of TypeScript with TS Language Service API and incremental compilation, that is important for develop with `watch` option.

Currently we should to use some external utils, like [rollup-plugin-gulp](https://github.com/Permutatrix/rollup-plugin-gulp) (that didn't work for me), or use SystemJS to load ES modules directly and build production bundle from these files.
But all these things must be inside this plugin – just plug and work.

**Comment by ezolenko** [comment]
I just published a rewrite for a similar reason (not showing any semantic or syntactic errors). https://github.com/ezolenko/rollup-plugin-typescript2

Might work in watch mode too, but haven't tried it yet...

**Comment by PaulBGD** [comment]
This plugin already works with `rollup-watch` for incremental building, however I'm looking at https://github.com/ivogabe/gulp-typescript to see how we can support TypeScript's internal incremental compilation.

**Comment by PaulBGD** [comment]
#91 now uses the TypeScript language server and supports incremental compilation.

Closing issues that I've integrated into #91, will be merged into master soon.
