### ISSUE TITLE
Add support for object __rest helper when using custom typescript 2.1

### ISSUE THREAD

**Issue by tabanliviu** [rollup/rollup-plugin-typescript#81]
Typescript 2.1 introduced support for [object spread and rest](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#object-spread-and-rest)

Using a custom typescript library fails because the `__rest` helper is not added to the build file (see [here](https://github.com/rollup/rollup-plugin-typescript/blob/be1278243c6b5246780e766bc28b7cd405ce8b83/src/index.js#L146))

PS: this does bring up an important issue for future compatibility with other features that require helpers. Is there a better way planned to load helpers from typescript directly instead of copying them in the plugin source?

**Comment by MattiasBuelens** [comment]
TypeScript now has [support for an external helpers library](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-external-helpers-library-tslib) published as `tslib` on npm (also on [GitHub](https://github.com/Microsoft/tslib/)) by using the `--importHelpers` compiler option. It may be interesting if this rollup plugin could use this new compiler option when using TypeScript 2.1 or higher, or at least pull the helpers from the official `tslib` package (perhaps as a peer dependency?).

**Comment by PaulBGD** [comment]
Closing issues that I've integrated into #91, will be merged into master soon.
