### ISSUE TITLE
Missing support for the `__generator` helper

### ISSUE THREAD

**Issue by dcherman** [rollup/rollup-plugin-typescript#85]
Running the code on this example (https://www.typescriptlang.org/play/index.html#src=(async%20function%20()%20%7B%0D%0A%0D%0A%7D)%3B) through this rollup plugin seems to not emit the `__generator` helper.

**Comment by dmitry-korolev** [comment]
You should upvote #75 
It's waiting for approval for a month already

**Comment by PaulBGD** [comment]
Closing issues that I've integrated into #91, will be merged into master soon.
