### ISSUE TITLE
Has this been abandoned? Alternatives?

### ISSUE THREAD

**Issue by TheBosZ** [rollup/rollup-plugin-typescript#90]
Typescript is now up to 2.3 while this is still stuck on 1.8.

I've tried setting my own Typescript version, but Rollup fails to generate valid JS.

This is related to #50 and #81

**Comment by ezolenko** [comment]
I made my [own version](https://github.com/ezolenko/rollup-plugin-typescript2) (main reason was error checking).

It has its own class of problems due to different approach (speed, cache related issues and corner cases), but works ok in general case. Needs recent rollup and typescript 2+.

**Comment by ncphillips** [comment]
There's also the fork by @alexlur https://github.com/alexlur/rollup-plugin-typescript

**Comment by PaulBGD** [comment]
The best fix I've found is just installing your own version of typescript and passing that to this plugin.

**Comment by alex-kinokon** [comment]
I am actively maintaining my fork, if that matters.

**Comment by PaulBGD** [comment]
I've been given publishing access, currently working on updating the package. Feedback is requested at #91.

**Comment by constfun** [comment]
FYI, @ezolenko's plugin is the only one that actually stops the build (and reports errors) on syntax errors for me. Thank you!
