### ISSUE TITLE
Overwrites .bin/tsc.cmd

### ISSUE THREAD

**Issue by AllNamesRTaken** [rollup/rollup-plugin-typescript#94]
After installing it overwrites node_modules/.bin/tsc.cmd meaning that any script in package.json that just do a tsc, like tests, now picks an old 1.8 version.

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\rollup-plugin-typescript\node_modules\typescript\bin\tsc" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\rollup-plugin-typescript\node_modules\typescript\bin\tsc" %*
)
```

It should leave the original.

**Comment by eldenpark** [comment]
Same happened. Command `tsc` in local repository now directs to that file. You can check, for example, by adding a script in package.json `which tsc && tsc -version`

**Comment by stakx** [comment]
This could be resolved if this plugin package declared `typescript` as a peer dependency so it would use *your* pick of that package.
