### ISSUE TITLE
Output is in es6 despite tsconfig?

### ISSUE THREAD

**Issue by JasonKleban** [rollup/rollup-plugin-typescript#95]
I'm trying to get Framework7 into Typescript, and part of that means adapting the current gulp build scripts.

https://github.com/JasonKleban/Framework7/tree/v2

`npm run build` seems to work, except it is outputting es6, despite the tsconfig.json.

`npm run dist` fails because uglify can't deal with the es6 output.

I'm forcing the use of the latest typescript and I wonder if that interferes with the use of tsconfig.json?

Thanks!

**Comment by zulaica** [comment]
It looks like you're targeting `es2015` (es6) in your `.tsconfig`. Try changing the target to `es5` and see if that helps?

**Comment by JasonKleban** [comment]
Arg!  True, that's my shotgun-style debugging that I accidentally committed, but even when es5 was the choice it acted the same.

**Comment by zulaica** [comment]
Ah, gotcha. I believe this plugin isn't compatible with the latest TypeScript? (I could totally be wrong; that's my understanding).

**Comment by JasonKleban** [comment]
Maybe, but why would *this* be the part that breaks?  Nothing between tsconfig and `target` changed recently.

**Comment by lukastaegert** [comment]
For rollup-bundling, the target must ALWAYS be either `es2015` or `esnext` as rollup needs this module format for its own bundling. If you want a different output format, you need to specify if via rollup's own `format` option. Not sure how to do this via gulp, though.

**Comment by sntran** [comment]
I can also confirm this.

With this simple module:

```es6
let foo = "foo";
console.log(foo);
```

Rollup with `rollup-plugin-typescript` produces:

```js
(function () {
        'use strict';

        let foo = "foo";
        console.log(foo);

}());
```

I would expect `let` become `var`.

Running the module directly with `rollup` CLI provides the same result.

However, when running with `tsc`, the module is transpired correctly:

```shell
tsc test.js --allowJs --target es5 --outDir dist
```

**Comment by lukastaegert** [comment]
Since this is a JS file, you will explicitly need to tell rollup-plugin-typescript to handle JS files as well. By default, this plugin will ignore .js files. E.g. via `typescriptPlugin({ include: '**/*.{ts,js}' })`

**Comment by sntran** [comment]
<del>
I figured out the reason for my case by debugging https://github.com/rollup/rollup-plugin-typescript/blob/6c433a6c482e3f36f01c83c5be130387da699c9c/src/index.js#L90.

My source file is not a `.ts` file so it did not pass the filter.

I added `include` option to `rollup-plugin-typescript` and the source is transpired through `typescript` now.

</del>

What @lukastaegert said :)

**Comment by lukastaegert** [comment]
Could be related to the original issue as well...

**Comment by sntran** [comment]
Kinda related, would it be possible to pass the option for `createFilter` through this plugin? My source files may not be relative to `process.cwd()`.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
