### ISSUE TITLE
Zero-byte in output

### ISSUE THREAD

**Issue by StreetStrider** [rollup/rollup-plugin-typescript#96]
Hello, I'm experimenting with this plugin, and trying to achieve smooth experience both for frontend and backend builds.

For now I got pretty simple setup for «backend»:
```js
return rollup(
{
	entry: entry, // '.ts' file
	external: id => id !== entry, // mark everything as external
	plugins: ts(
	{
		typescript: require('typescript')
	}),
})
.then(bundle =>
{
	return bundle.generate(
	{
		format:  'cjs',
		exports: 'auto',
	})
})
```
Somehow NUL-byte is inserted inside `require('typescript-helpers');`.
I see `'\'use strict\';\n\nrequire(\'\u0000typescript-helpers\');\n…` when I debug output.
What on earth could cause this weird insertion to happen?

* `rollup@0.49.2`
* `rollup-plugin-typescript@0.8.1`
* `typescript@2.5.2`
* node `v7.5.0`

**Comment by StreetStrider** [comment]
I believe this happens when `typescript-helpers` are marked as external. I got similar build but with dependencies bundled (for frontend target) and it bundles just ok.

**Comment by StreetStrider** [comment]
This is not a critical, cause I just replace zero-byte with empty string, but definitely it would be interesting to track this down.
@Rich-Harris

**Comment by StreetStrider** [comment]
Actually, I found this is done by intent. 🤔 
https://github.com/rollup/rollup-plugin-typescript/blob/be1278243c6b5246780e766bc28b7cd405ce8b83/src/index.js#L23-L24
Maybe this works in frontend bundles, but when the target is cjs/node it leads to corruption of every file which includes `typescript-helpers` which means, every file. Is it an ugly workaround?

**Comment by stakx** [comment]
Yes, this is intentional, and probably done because of what Rollup's documentation recommends to plugin authors in https://github.com/rollup/rollup/wiki/Plugins#conventions:

> If your plugin uses 'virtual modules' (e.g. for helper functions), prefix the module ID with `\0`. This prevents other plugins from trying to process it.

Replacing this plugin's own helper functions with `ts-lib` and `--importHelpers` would get rid of that "virtual module" and the NUL character.
